### ISSUE TITLE
Watching doesn't work when you haven't made a .css yet

### ISSUE THREAD

**Issue by ghost** [less/less.ruby#1]
So basically, you need to have the .css file compiled before you can run the --watch command, otherwise it gives you an error saying the CSS isnt there. Expected behavior is: if .css isnt there, compile it once and start watching.

**Comment by cloudhead** [comment]
fixed in 0.7.5

**Comment by ghost** [comment]
Err, still gives me errors. Here it is:

Watching for changes in something.less ...Ctrl-C to abort.
/usr/local/lib/ruby/gems/1.8/gems/less-0.8.1/bin/../lib/less/command.rb:31:in `stat': No such file or directory - something.css (Errno::ENOENT)
    from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.1/bin/../lib/less/command.rb:31:in`run!'
    from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.1/bin/../lib/less/command.rb:27:in `loop'
    from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.1/bin/../lib/less/command.rb:27:in`run!'
    from /usr/local/lib/ruby/gems/1.8/gems/less-0.8.1/bin/lessc:62
    from /usr/local/bin/lessc:19:in `load'
    from /usr/local/bin/lessc:19

**Comment by cloudhead** [comment]
fixed in 0.8.7

**Comment by rosejn** [comment]
I just updated to the latest gem, and I still get this error.  I have a pre-compiled css file, and it will correctly watch it for 10 or 20 (seems random) updates, and then suddenly crash.  Same error as above.  I'm editing the file in Vim, saving, and then refreshing in the browser.  Really annoying when it keeps crashing like this.

**Comment by cloudhead** [comment]
I've actually been having this problem I think since I upgraded to 10.6, I'm pretty sure it's unrelated to Less though, as I've had the same error with watchr.. I have no idea what's causing this, as the file actually exists in my case.

It's a different problem though, than this issue.
