### ISSUE TITLE
Ruby error when using variable inside of -webkit or -moz functions

### ISSUE THREAD

**Issue by soffes** [less/less.ruby#120]
If you try to create the following mixin (or assign the following properties to a selector):

```
    .background-gradient(@top-color: #fff, @bottom-color: #ddd) {
      background: @bottom-color;
      background-image: -moz-linear-gradient(top, bottom, from(@top-color), to(@bottom-color));
      background-image: -webkit-gradient(linear, left top, left bottom, color-stop(0.00, @top-color), color-stop(1.00, @bottom-color));
    }
```

`engine/nodes/property.rb:111` will throw the following error:

> You have a nil object when you didn't expect it!
> The error occurred while evaluating nil.nearest

I started to debug it and noticed that the properties parent is nil. If you nest a variable inside of a -webkit or -moz function, it will fail.

**Comment by jpdutoit** [comment]
This issue was preventing my use of Less for a theme with many gradients, so i tried to fix this problem. The following diff is the result (applied to 1.2.17). I'm not a Ruby developer, nor am i familiar with the codebase, so I'm not sure if this is the best (or correct) way of doing this. But in my tests it seemed to solve the above problem. 

edit: formatting

```
=== modified file 'lib/less/engine/nodes/function.rb'
--- lib/less/engine/nodes/function.rb 2009-12-01 16:40:26 +0000
+++ lib/less/engine/nodes/function.rb 2009-12-01 17:16:08 +0000
@@ -66,6 +66,10 @@
        self.evaluate(env).to_css
      end

+      def nearest node
+        parent.nearest node
+      end
+
      #
      # Call the function
      #
@@ -76,9 +80,9 @@
        if Functions.available.include? self.to_sym
          send to_sym, *@args
        else
-          Node::Anonymous.new("#{to_sym}(#{@args.map(&:to_css) * ', '})")
+          Node::Anonymous.new("#{to_sym}(#{@args.map{|e| e.to_css(context); e.evaluate(context)} * ', '})")
        end
      end
    end

=== modified file 'lib/less/engine/nodes/property.rb'
--- lib/less/engine/nodes/property.rb 2009-12-01 16:40:26 +0000
+++ lib/less/engine/nodes/property.rb 2009-12-01 17:02:52 +0000
@@ -170,6 +170,7 @@
      def to_css env = nil
#        puts "TOCSS, delim: |#{@delimiter}|"
        map do |i|
+          i.parent = self.parent
          i.respond_to?(:to_css) ? i.to_css() : i.to_s
        end * @delimiter
      end
@@ -217,6 +218,8 @@
        elsif size == 1
          if first.is_a? Variable
            first.evaluate(env)
+          elsif first.is_a? Function
+            first.evaluate(env)
          else
            first
          end
```

**Comment by soffes** [comment]
I [fixed this](http://github.com/samsoffes/less/commit/85e0d78d934f1d0eba9c28e7fa0ffdd23f43526c) and [wrote a test](http://github.com/samsoffes/less/commit/1692aac5913ad2219faa5a445d4d4a2f0533f728) on [my fork](http://github.com/samsoffes/less). Everything works great!

**Comment by jpdutoit** [comment]
Thanks for adding it to a fork, I don't know how to do that yet. I noticed that in your fix, you left out the second change in function.rb. In my test case this causes problems in dynamix mixins.

edit: Hopefully fixed markdown issues with colors (nope, it didnt, im removing the hashes from the color definitions)

With this less file:

```
@globalColor: 010101;

.gradient (@localColor: 030303) {
  background: -webkit-gradient(linear, left top, left bottom, from(@localColor), to(@globalColor));
}

.test1 {.gradient; }
.test2 { .gradient(020202); }
```

I then get this result:

```
.test1, .test2 { background: -webkit-gradient(linear, left top, left bottom, from(030303), to(010101)); }
```

Instead of:

```
.test1 { background: -webkit-gradient(linear, left top, left bottom, from(030303), to(010101)); }
.test2 { background: -webkit-gradient(linear, left top, left bottom, from(020202), to(010101)); }
```

**Comment by soffes** [comment]
Interesting. I had trouble getting it to work with the second change. i'll take another look.

**Comment by soffes** [comment]
After [testing a bit](http://github.com/samsoffes/less/commit/0afa0270c20844729f010e8b8efb3557efb89f5e), your second change breaks a ton of tests. i am seeing your issue though. `.test2` isn't using `#020202`, but `#030303`, which is incorrect. I am working on a fix.

**Comment by cloudhead** [comment]
fixed @ 1.2.18, thanks to samsoffes

**Comment by jpdutoit** [comment]
cloudhead: I noticed that you only included part of the fix for issue #120. Using a variable in -webkit or -moz functions then still fails in dynamic mixins (as described above). The follow-up fixes to that is also in samsoffes' branch.

**Comment by cloudhead** [comment]
Yea, the other commits couldn't be applied through the fork queue, I'm guessing there's conflicts. I'm going to try to merge them manually.

**Comment by cloudhead** [comment]
done @ 1.2.19

**Comment by soffes** [comment]
Thanks cloudhead and jpdutoit!
